version: "3.7"

services:
  juridicoicacehidalgo.mx:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: juridicoicacehidalgo.mx
    volumes:
      - ./public_html:/var/www/html
    restart: always
    networks:
      - npm
      - juridicoicacehidalgo.mx-net

networks:
  juridicoicacehidalgo.mx-net:
    name: juridicoicacehidalgo.mx-net
    driver: bridge
  npm:
    external: true